name: ticket_app
description: "A Help Desk Ticketing System app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.7

  # Navigation
  go_router: ^13.0.0

  # Local Storage
  sqflite: ^2.3.0
  path: ^1.9.0

  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  share_plus: ^9.0.0
  mocktail: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  flutter_lints: ^3.0.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
